name = "cloudflare-docker-proxy"
main = "dist/main.js"              # ← 新增：指向 webpack 产物
compatibility_date = "2023-12-01"

# 顶层变量（可选，把原来的 [env.vars] 挪到这里）
[vars]
CUSTOM_DOMAIN = "libcuda.so"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

# 开发环境变量
[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "docker.161798.xyz"      # ← 修正拼写

# 生产环境
[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.libcuda.so", custom_domain = true },
#   { pattern = "quay.libcuda.so", custom_domain = true },
#   { pattern = "gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s.libcuda.so", custom_domain = true },
#   { pattern = "ghcr.libcuda.so", custom_domain = true },
#   { pattern = "cloudsmith.libcuda.so", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

# 预发布（可选）
[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
